### ISSUE TITLE
PLEASE USE MATCH CASE

### ISSUE THREAD

**Issue by nickoncrack** [archisha69/physics-solver#1]
```py
match variable:
    case a:
        # code
    case b:
        # code2
```

same as:
```py
if variable == a:
    # code
elif variable == b:
    # code2
```

**Comment by XyrenTheCoder** [comment]
> ```python
> match variable:
>     case a:
>         # code
>     case b:
>         # code2
> ```
> 
> same as:
> 
> ```python
> if variable == a:
>     # code
> elif variable == b:
>     # code2
> ```

ok but why would i use match case

**Comment by XyrenTheCoder** [comment]
also im using 3.9
lmao

**Comment by XyrenTheCoder** [comment]
dead
